version: "3.8"

services:
  app-dev:
    build:
      context: ../
      dockerfile: Docker/Dockerfile

    env_file:
      - ../.env
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: phoneguardian
    volumes:
      - postgresql-db:/var/lib/postgresql/data/
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

volumes:
  postgresql-db:
